# fly.toml app configuration file generated for maprater on 2023-10-12T22:04:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maprater"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[processes]
  app = ""

[[mounts]]
  source = "maprater_data"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
