# fly.toml file generated for maprater on 2022-09-02T17:13:38+01:00

app = "maprater"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
source = "maprater_data"
destination = "/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
